### ISSUE TITLE
Resize issue with different CSS sizes

### ISSUE THREAD

**Issue by iantsch** [iantsch/esnext-slider#4]
Slides aren't resized properly if the size base is changes with CSS media queries.

```scss
.slider__slide {
  width: 260px;
  @media (min-width: 768px) {
    width: 280px
  }
  @media (min-width: 1280px) {
    width: 360px
  }
}
```
